### ISSUE TITLE
.ini БД.

### ISSUE THREAD

**Issue by mrlead** [mrlead/Intern#1]
Работаю над парсером для чтения ini файлов, удобно и просто в использовании, будет легко делать языки для программы

**Comment by mrlead** [comment]
Парсер готов, теперь он будет локализатором приложения.

**Comment by mrlead** [comment]
В программе планируется использовать три языка: русский (как основной язык), английский и итальянский(под вопросом, т.к. возможна не стыковка под раскладку клавиатуры).

**Comment by mrlead** [comment]
На данный момент ведётся работа над русским языком.

**Comment by 4erDak** [comment]
Красава, чё)

**Comment by mrlead** [comment]
Спасибо)
